/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vv4HazoSKR9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vv4HazoSKR9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these fonts, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export async function LandingPage() {
// const categories = await fetch("http://vack.ddev.site/api/categories")
// const products = await fetch("http://vack.ddev.site/api/products")

// if (!categories.ok) {
//   throw new Error("Failed to fetch data")
// }
// if (!products.ok) {
//   throw new Error("Failed to fetch data")
// }
// const category = await categories.json()
// const product = await products.json()

  return (
    <div className="flex flex-col min-h-[100dvh] font-light">
      <main className="flex-1">
        <section className=" relative bg-gradient-to-r from-black via-gray-500 to-black py-12 md:py-20">
        
        <section className=" relative bg-gradient-to-r from-black via-gray-500 to-black py-12 md:py-20">
        
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid md:grid-cols-2 gap-8 items-center">
              <div>
                <h1 className="text-3xl md:text-5xl font-bold mb-4 ">
                  Welcome to <strong className="text-black font-medium">ROAR .</strong>
                </h1>
                <p className="text-gray-400 mb-6">
                  Old School training facility that focuses on quality, not quantity.
                </p>
                <div className="flex gap-4">
                  <Link href="/shop">
                    <Button size="lg" className="font-sans">Shop Now</Button>
                  </Link>
                    <Button size="lg" className="font-sans">Shop Now</Button>
                  </Link>
                  <Link href="/about">
                    <Button size="lg" variant="outline" className="font-sans">
                    <Button size="lg" variant="outline" className="font-sans">
                      Learn More
                    </Button>
                  </Link>
                </div>

              </div>
                <div className="p-4 relative">
                  <h3 className="text-lg text-black  font-sans mb-2">Protein Bars</h3>
                  <p className="text-gray-600 mb-4">High-quality protein bars to fuel your workouts.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-gray-900 font-bold">$24.99</span>
                    <Button className="font-sans absolute bottom-2 right-2" size="sm">View Details</Button>
                  </div>
                </div>
              
              <div className="bg-white rounded-lg shadow-md overflow-hidden">
                <img
                  alt="Product"
                  className="w-full h-48 object-cover"
                  height="300"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4 relative">
                  <h3 className="text-lg text-black   font-sans mb-2">Fitness Apparel</h3>
                  <p className="text-gray-600 mb-4">Comfortable and stylish fitness clothing with gret quality.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-gray-900 font-bold">$39.99</span>
                    <Button className="font-sans absolute bottom-2 right-2" size="sm">View Details</Button>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-md overflow-hidden">
                <img
                  alt="Product"
                  className="w-full h-48 object-cover"
                  height="300"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4 relative">
                  <h3 className="text-lg text-black  font-sans mb-2">Resistance Bands</h3>
                  <p className="text-gray-600 mb-4">Versatile resistance bands for strength training.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-gray-900 font-bold">$14.99</span>
                    <Button className="font-sans absolute bottom-2 right-2" size="sm">View Details</Button>
                  </div>
                </div>
              </div>
              <div className="bg-white rounded-lg shadow-md overflow-hidden">
                <img
                  alt="Product"
                  className="w-full h-48 object-cover"
                  height="300"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/300",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4 relative">
                  <h3 className="text-lg text-black  font-sans mb-2">Fitness Accessories</h3>
                  <p className="text-gray-600 mb-4">Enhance your workout with our fitness accessories.</p>
                  <div className="flex items-center justify-between">
                    <span className="text-gray-900 font-bold">$9.99</span>
                    <Button className="font-sans absolute bottom-2 right-2" size="sm">View Details</Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gradient-to-r from-black via-gray-500 to-black py-12 md:py-20">
          <div className="container mx-auto px-4 md:px-6">
            <h2 className="text-2xl md:text-3xl font-bold mb-8 font-sans ">Shop by Category</h2>
            {/* {categories && categories.data.map((category) => (
              <Link
                className="bg-white rounded-lg shadow-md overflow-hidden"
                href={`/category/${category.slug}`}
                key={category.id}
              >
                <img
                  alt="Category"
                  className="w-full h-40 object-cover"
                  height="200"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4">
                  <h3 className="text-lg font-bold mb-2">{category.category}</h3>
                  <p className="text-gray-600">{category.description}</p>
                </div>
              </Link>
            ))} */}
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
              <Link className="bg-white rounded-lg shadow-md overflow-hidden " href="#">
                <img
                  alt="Apparel"
                  className="w-full h-40 object-cover"
                  height="200"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4">
                  <h3 className="text-xl text-center text-black font-sans mb-2 font-medium">Apparel</h3>

                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden" href="#">
                <img
                  alt="Supplements"
                  className="w-full h-40 object-cover"
                  height="200"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4">
                  <h3 className="text-xl text-center text-black font-sans mb-2 font-medium">Supplements</h3>

                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden" href="#">
                <img
                  alt="Accessories"
                  className="w-full h-40 object-cover"
                  height="200"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4">
                  <h3 className="text-xl text-center text-black  font-sans mb-2 font-medium">Accessories</h3>

                </div>
              </Link>
              <Link className="bg-white rounded-lg shadow-md overflow-hidden" href="#">
                <img
                  alt="Equipment"
                  className="w-full h-40 object-cover"
                  height="200"
                  src="/slide.png"
                  style={{
                    aspectRatio: "300/200",
                    objectFit: "cover",
                  }}
                  width="300"
                />
                <div className="p-4">
                  <h3 className="text-xl text-center text-black font-sans mb-2 font-medium">Equipment</h3>

                </div>
              </Link>
            </div>
          </div>
        </section>
        
      </main>
    </div>
  );
}

function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}

export default LandingPage;
